### ISSUE TITLE
Crashed after executing the command

### ISSUE THREAD

**Issue by spance** [xo/usql#464]
```shell
~$ ./usql_static -V
usql 0.19.1
~$ ./usql_static
Type "help" for help.

panic: runtime error: slice bounds out of range [:43] with capacity 32

goroutine 1 [running]:
github.com/xo/usql/stmt.(*Params).Get(0xc00077c720, 0xc00173ea48)
        github.com/xo/usql/stmt/params.go:86 +0x9fb
github.com/xo/usql/stmt.(*Params).GetAll(0xc00077c720, 0xc00173ea48)
        github.com/xo/usql/stmt/params.go:97 +0x55
github.com/xo/usql/metacmd.(*Params).GetAll(0xc000c320c0, 0x1)
        github.com/xo/usql/metacmd/types.go:202 +0x192
github.com/xo/usql/metacmd.init.0.func15(0xc000c320c0)
        github.com/xo/usql/metacmd/cmds.go:442 +0x178
github.com/xo/usql/handler.(*Handler).Run.Decode.func3({0x6e2e518, 0xc001677200})
        github.com/xo/usql/metacmd/metacmd.go:26 +0xd8
github.com/xo/usql/metacmd.RunnerFunc.Run(0x585b8e0?, {0x6e2e518?, 0xc001677200?})
        github.com/xo/usql/metacmd/types.go:82 +0x4d
github.com/xo/usql/handler.(*Handler).Run(0xc001677200)
        github.com/xo/usql/handler/handler.go:282 +0xb30
main.Run({0x6dd1b40, 0xada1340}, 0xc0010e5a70, 0xc000ca12c0, {0xc000eff020, 0x23})
        github.com/xo/usql/run.go:355 +0xce2
main.New.func3(0xc001407808?, {0xada1340?, 0x7?, 0x6077847?})
        github.com/xo/usql/run.go:126 +0x185
github.com/spf13/cobra.(*Command).execute(0xc001407808, {0xc0000740a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc001407808)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0xc0000740a0?, {0x6dd1b40?, 0xada1340?})
        github.com/spf13/cobra@v1.8.0/command.go:1032 +0x47
main.main()
        github.com/xo/usql/main.go:40 +0x13c
```

**Comment by nineinchnick** [comment]
What's in your `$HOME/.usqlrc`? What's `usql_static` - how did you build it?

**Comment by spance** [comment]
The `.usqlrc` is an empty file, and the `usql_static` was downloaded from https://github.com/xo/usql/releases/download/v0.19.1/usql_static-0.19.1-linux-amd64.tar.bz2

**Comment by spance** [comment]
I tried many times and finally found the problem.
My config file `$HOME/.config/usql/config.yaml` like this:
```yaml
connections:
  xxx: xxxx
init: |
  \echo date `date`
```
Then after deleting the `init` fragment, no errors were reported.

**Comment by kenshaw** [comment]
I'll look in to this shortly. Probably a simple oversight on my part.

**Comment by kenshaw** [comment]
I'm not able to reproduce this error:

```sh
ken@ken-desktop:~/Downloads$ mkdir usql
ken@ken-desktop:~/Downloads$ cd usql/
[config.yaml.txt](https://github.com/xo/usql/files/15292979/config.yaml.txt)
ken@ken-desktop:~/Downloads/usql$ mv ../usql_static-0.19.1-linux-amd64.tar.bz2 .
ken@ken-desktop:~/Downloads/usql$ tar -jxvf usql_static-0.19.1-linux-amd64.tar.bz2 
usql_static
LICENSE
ken@ken-desktop:~/Downloads/usql$ md5sum usql_static
c110e337bb43dd359c34813bb459366c  usql_static
ken@ken-desktop:~/Downloads/usql$ ./usql_static 
Type "help" for help.

date Mon May 13 05:18:34 PM WIB 2024
(not connected)=> \q
ken@ken-desktop:~/Downloads/usql$ cat ~/.config/usql/config.yaml 
---
init: |
  \echo date `date`
ken@ken-desktop:~/Downloads/usql$ ./usql_static -V
usql 0.19.1
ken@ken-desktop:~/Downloads/usql$ 
```

Can you please share your exact yaml config file? Note that GitHub doesn't seem to allow uploads of .yaml extensions, for whatever reason. You'll need to rename the file prior to upload.

[config.txt](https://github.com/xo/usql/files/15292990/config.txt)

**Comment by kenshaw** [comment]
Are you perhaps using something like Windows encoding? With `\r\n` line endings? I've tried all manner of variations and I can't cause that same block of code to escape under any input that I could come up with. I'm sure my code is bad, but it's going to be difficult to figure out the cause of this without the exact character sequence/input.

Are you able to get `\echo` to work in the `init:` stanza in a simpler form? For example:

```yaml
init: '\echo hi'
```

Which has this output on my system:

```sh
$ usql
Type "help" for help.

hi
(not connected)=> \q
```

**Comment by spance** [comment]
Now I found the cause of this problem, because the output of the `date` command contains some unicode characters, causing the variable `i` calculation in the `Params.Get()` method to become longer.
There is my simple fix:
```go
i = start + len([]rune(z)) - 1
```
